/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InboxView.java
 *
 * Created on Jun 5, 2011, 4:19:44 PM
 */
package com.app.lifeNet;

import java.awt.Color;
import java.awt.Component;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JTextArea;
import javax.swing.ListCellRenderer;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author hrushi
 */
public class InboxView extends javax.swing.JFrame {

    DefaultListModel listModel;

    /** Creates new form InboxView */
    public InboxView() {
        initComponents();


        listModel = new DefaultListModel();
        jList1.setModel(listModel);

        //jList1.setCellRenderer(new JListTextAreaCellRenderer());

        listModel.clear();

        if (MessageQueue.unreadCount == 0) {
            listModel.addElement("No messages");

        } else {
            for (int i = 0; i < MessageQueue.unreadCount; i++) {
                ChatMessage msg = (ChatMessage) MessageQueue.unreadMessageVector.elementAt(i);
                System.out.println(i + ":" + MessageQueue.unreadCount + ":" + msg.payload + msg.rxTime.toString());
                System.out.flush();
                listModel.addElement("[" + msg.rxTime.toString() + "] " + msg.srcName + "\n" + msg.payload);
            }
        }

        MessageQueue.newMsgReadFlag = true;
        jList1.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Messages");
        setResizable(false);

        jList1.setFont(new java.awt.Font("Bitstream Charter", 0, 11)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public class JListTextAreaCellRenderer extends JTextArea implements ListCellRenderer {

        public JListTextAreaCellRenderer() {
            setOpaque(true);
            this.setUI(new javax.swing.plaf.basic.BasicTextAreaUI());
            this.setWrapStyleWord(true);
            this.setLineWrap(true);
            this.setAutoscrolls(true);

        }

        public Component getListCellRendererComponent(
                JList list,
                Object value,
                int index,
                boolean isSelected,
                boolean cellHasFocus) {

// return super(getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

            setText(value.toString());
            setBackground(isSelected ? Color.blue : Color.white);
            setForeground(isSelected ? Color.white : Color.black);
            return this;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
