#!/bin/sh
exec 2> ./tmp.install.errorlog.`date`

INSTALL_DIR=`cat config/install_path.conf` 

rm -r $INSTALL_DIR 1> /tmp/install_log1
rm -r $HOME/.LifeNetData 1> /tmp/install_log1

mkdir $INSTALL_DIR 1> /tmp/install_log1
mkdir $INSTALL_DIR/config 1> /tmp/install_log1
mkdir $HOME/.LifeNetData 1> /tmp/install_log1

cp applications/Inject/dist/Debug/GNU-Linux-x86/inject /bin
cp applications/Sniff/dist/Debug/GNU-Linux-x86/sniff /bin
cp applications/PathTraceLogger/dist/Debug/GNU-Linux-x86/pathtracelogger /bin
cp scripts/lifenet_start /bin
cp scripts/lifenet_stop /bin

cp -r config/ $INSTALL_DIR/config/
cp -r config/ $HOME/.LifeNetData/
cp -r firewall/ $HOME/.LifeNetData/
cp mymanet.conf $HOME/.LifeNetData/config
cp -r src/manifold.ko $HOME/.LifeNetData/

echo "\nLifeNet has now been installed on your system.\nYou can use the following commands to start or stop LifeNet.\n-> lifenet_start\n-> lifenet_stop\n"

