#!/bin/bash

echo -e "\n============ LifeNet_Beta 1.0 unload utility ============"

sudo touch $APP_DATA_PATH/install_log
sudo rmmod manifold
sudo killall -9 inject 
sudo killall -9 sniff

echo "Done"

